Name : Bijay Gurung

UniID: 2357590

Class: L6CG19

Task 1: Create a python program that converts between different units of measurement.

In [ ]:
def main():
  """
  Here, it ask user to select the conversion type and again it ask user to input the value after that it perform the conversion and display the result.
  """
  print("Select the Conversion Type")
  print("\n1. Length")
  print("2. Weight")
  print("3. Volume")
  print("4. quit\n")

  while True:
    try:
      choice = int(input(">"))
      if (choice == 4):
        break
      elif (choice==0 or choice>4):
        print("Please enter the number from the given option")
        continue
      break
    except ValueError:
      print("Please enter the number from the given option")

  if(choice == 1):
    while True:
      try:
        print("\nEnter Length in meter: ")
        l = float(input(">"))

        #Converting from m to ft
        ft = l * 3.28084
        print(f"ft: {ft}")
        break
      except ValueError:
        print("Please Enter the Length in meter")
    return l


  elif(choice == 2):
    while True:
      try:
        print("\nEnter Weight in Kilogram: ")
        w = float(input(">"))

        #Converting from kg to lbs
        lbs = w * 2.20462
        print(f"lbs: {lbs}")
        break
      except ValueError:
        print("Please enter the weight in Kilogram")
    return w

  elif(choice == 3):
    while True:
      try:
        print("\nEnter Volume in liters: ")
        v = float(input(">"))

        #Converting from l to gal
        gal = v * 0.264172
        print(f"gal: {gal}")
        break
      except ValueError:
        print("Please enter the Volume in liters")

if __name__ == "__main__":
  main()

Select the Conversion Type

1. Length
2. Weight
3. Volume
4. quit

>1

Enter Length in meter: 
>10
ft: 32.8084


Task2: Create a python program that performs various mathematical operations on a list of numbers.

In [ ]:
def choice():
  print("Choose from the given option\n")
  print("1. Sum\n")
  print("2. average\n")
  print("3. maximum\n")
  print("4. minimum\n")
  print("5. quit")

  while True:
    try:
      choice = int(input(">"))

      if(choice<1 or choice>5):
        print("Please select from the given option")
        continue

      if(choice == 5):
        break

      break
    except ValueError:
      print("Please select from the given option")
  return choice


def sumNumbers(choice):
  """
  Here, it calculate the sum of the list of number
  """
  if(choice ==1):
    numList = []
    print("Enter the lists of number")
    while True:
      n = input(">")
      if(n.lower() == "done"):
        break
      num = int(n)
      numList.append(num)

    totalSum = 0
    for i in numList:
      totalSum += i
    print(f"Sum: {totalSum}")


choice = choice()
sumNumbers(choice)

def averageNumbers(choice):
  """
  Here, it calculates the average of the list of number
  """
  if(choice ==2):
    numList = []
    print("Enter the lists of number")
    while True:
      n = input(">")
      if(n.lower() == "done"):
        break
      num = int(n)
      numList.append(num)

    totalSum = 0
    for i in numList:
      totalSum += i

    totalAverage = totalSum/len(numList)
    print(f"Average: {totalAverage}")

averageNumbers(choice)

def maxNumbers(choice):
  """
  Here, it calculates the maximum of the list of number
  """
  if(choice==3):
    numList = []
    max = 0
    print("Enter the lists of number")
    while True:
      n = input(">")
      if(n.lower() == "done"):
        break
      num = int(n)
      numList.append(num)

    max = numList[0]
    for i in numList:
      if(i>max):
        max = i
    print(f"Maximum: {max}")

maxNumbers(choice)

def minNumbers(choice):
  """
  Here, it calculates the minimum of the list of number
  """
  if(choice==4):
    numList = []
    max = 0
    print("Enter the lists of number")
    while True:
      n = input(">")
      if(n.lower() == "done"):
        break
      num = int(n)
      numList.append(num)

    min = numList[0]
    for i in numList:
      if(i<min):
        min = i
    print(f"Minimum: {min}")
minNumbers(choice)

Choose from the given option

1. Sum

2. average

3. maximum

4. minimum

5. quit
>2
Enter the lists of number
>1
>2
>3
>4
>5
>done
Average: 3.0


Task 3: Reverse a List using Slicing

In [ ]:
lst = [1,2,3,4,5]

def reverse_list(lst):
  """
  This function reverse the list using slicing
  """
  reverse = lst[::-1]
  print(reverse)
reverse_list(lst)

[5, 4, 3, 2, 1]


Task 4: Remove the first and last element

In [ ]:
lst = [1,2,3,4,5]

def remove_first_last(lst):
  """
  here, it remove the first and last element from the list using slicing
  """
  newlst = lst[1:4]
  print(newlst)

remove_first_last(lst)

[2, 3, 4]


Task 5: Get the first n Elements

In [ ]:
lst1 = [1,2,3,4,5]
n = int(input("Enter the number: "))

def get_first_n(ls1):
  newList = lst1[:n:]
  print(newList)

get_first_n(lst1)

Enter the number: 3
[1, 2, 3]


Task 6: Extract Element from the end

In [ ]:
lst = [1,2,3,4,5]
n = int(input("Enter the number: "))

def get_last_n(lst,n):
  newList = lst[-n::]
  print(newList)

get_last_n(lst,n)

Enter the number: 2
[4, 5]


Task 7: Extract Elements in Reverse Order

In [ ]:
lst = [1,2,3,4,5,6]

def reverse_skip(lst):
  new_list = lst[-2::-2]
  print(new_list)

reverse_skip(lst)

[5, 3, 1]


Exercise on Nested List

1. Flatten a Nested List

In [ ]:
lst = [[1,2], [3,4], [5]]

def flatten(lst):
  new_list = []
  for i in lst:
    for j in i:
      new_list.append(j)
  print(new_list)
flatten(lst)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements

In [ ]:
lst = [[1,2,3], [4,5,6], [7,8,9]]
indices = [1,2]

def access_nested_element(lst,indices):
  result = lst[indices[0]][indices[1]]
  print(result)
access_nested_element(lst, indices)

6


3. Sum of All Elements in a Nested List

In [ ]:
nested_list = [[1, 2], [3, [4, 5]], 6]

def sum_nested_element(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested_element(item)
        else:
            total += item
    return total

result = sum_nested_element(nested_list)
print(result)


21


4. Remove Specific Element from a Nested List

In [ ]:
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

def remove_element(lst, elem):
  for i in lst:
    if elem in i:
      i.remove(elem)
  print(lst)
remove_element(lst, elem)

[[1], [3], [4, 5]]


5. Find the maximum element in a nested list

In [ ]:
nested_list = [[1, 2], [3, [4, 5]], 6]

def find_max(lst):
    maximum = 0
    for i in lst:
        if isinstance(i, list):
            maximum = max(maximum, find_max(i))
        else:
            maximum = max(maximum, i)
    return maximum

result = find_max(nested_list)
print(result)


6


6.  Count Occurrences of an Element in a Nested List

In [ ]:
lst = [[1,2], [2,3], [2,4]]
elem = 2

def count_occurance(lst, elem):
  count = 0
  for i in lst:
    if isinstance(i, list):
      count += count_occurance(i, elem)
    else:
      if i == elem:
        count += 1
  return count
result = count_occurance(lst, elem)
print(result)

3


7. Flatten a List of Lists of Lists

In [ ]:
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

def deep_flatten(lst):
  newlst = []
  for i in lst:
    if isinstance(i, list):
      newlst.extend(deep_flatten(i))
    else:
      newlst.append(i)
  return newlst

result = deep_flatten(lst)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [ ]:
lst = [[1, 2], [3, 4], [5, 6]]

def average_nested(lst):
  newlst = []
  totalSum = 0

  for i in lst:
    for j in i:
      newlst.append(j)

  for k in newlst:
    totalSum += k

  average = totalSum/len(newlst)
  print(average)

average_nested(lst)


3.5


Numpy

Basic Vector and Matrix Operation with Numpy.

Problem 1: Array Creation

In [ ]:
import numpy as np

In [ ]:
# Initialize an empty array with size 2x2
emptyArr = np.empty((2,2))
print(f"Empty Array: {emptyArr}")

Empty Array: [[5.07863318e-316 0.00000000e+000]
 [5.33590898e-322 4.22972498e-307]]


In [ ]:
# Initialize an all ones array with size 4x2
oneArr = np.ones((4,2))
print(f"All Ones Array: {oneArr}")

All Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Return a new array of given shape and type, filled with a fill value
fillArr = np.full((3,3), 5)
print(f"Fill Array: {fillArr}")

Fill Array: [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# Return a new array of zeros with the same shape and type as a given array
arr = np.array([[1,2,3], [4,5,6]])
newArr = np.zeros_like(arr)
print(f"Zero Array: {newArr}")

Zero Array: [[0 0 0]
 [0 0 0]]


In [ ]:
# Return a new array of ones with same shape and type as a given array
arr = np.array([[1,2,3], [4,5,6]])
newArr = np.ones_like(arr)
print(f"Ones Array: {newArr}")

Ones Array: [[1 1 1]
 [1 1 1]]


In [ ]:
# For an existing list new_list = [1,2,3,4] convert to an numpy array
new_list = [1,2,3,4]
arr = np.array(new_list)
print(f"Numpy Array: {arr}")

Numpy Array: [1 2 3 4]


Problem 2

In [ ]:
# Create an array with values ranging from 10 to 49.
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Create a 3X3 matrix with values ranging from 0 to 8.
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 3X3 identity matrix.
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a random array of size 30 and find the mean of the array.
randomArr = np.random.random(30)
mean = np.mean(randomArr)
print(f"Mean: {mean}")

Mean: 0.5141679174763646


In [ ]:
# Create a 10X10 array with random values and find the minimum and maximum values.
randomMat = np.random.random((10,10))
min = randomMat.min()
max = randomMat.max()
print(f"Minimum: {min}")
print(f"Maximum: {max}")

Minimum: 0.006338869296837024
Maximum: 0.9906734414162869


In [ ]:
# Create a zero array of size 10 and replace 5th element with 1.
zeroArr = np.zeros(10)
zeroArr[4] = 1
print(zeroArr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Reverse an array arr = [1,2,0,0,4,0].
reverse = np.array([1,2,0,0,4,0])
reverse = reverse[::-1]
print(reverse)

[0 4 0 0 2 1]


In [ ]:
# Create a 2d array with 1 on border and 0 inside.
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create a 8X8 matrix and fill it with a checkerboard pattern.
cb = np.zeros((8,8))
cb[1::2, ::2] = 1
cb[::2, 1::2] = 1
print(cb)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem 3

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
# Add the two array
add = x + y
print(add)

[[ 6  8]
 [10 13]]


In [ ]:
# Subtract the two array
sub = v - w
print(sub)

[-2 -2]


In [ ]:
# Multiply the array with any integers of your choice
mul = x * 11
print(mul)

[[11 22]
 [33 55]]


In [ ]:
# Find the square of each element of the array
square = np.square(y)
print(square)

[[25 36]
 [49 64]]


In [ ]:
#  Find the dot product between: v(and)w ; x(and)v ; x(and)y
vw = np.dot(v,w)
print(vw)

219


In [ ]:
xv = np.dot(x,v)
print(xv)

[29 77]


In [ ]:
xy = np.dot(x,y)
print(xy)

[[19 22]
 [50 58]]


In [ ]:
# Concatenate x(and)y along row and Concatenate v(and)w along column. Hint:try np.concatenate() or np.vstack() functions.
concatXY = np.concatenate((x,y), axis=0)
print(concatXY)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
concatVW = np.vstack((v,w))
print(concatVW)

[[ 9 10]
 [11 12]]


In [ ]:
# Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
concatXV = np.concatenate((x,v), axis=0)
print(concatXV)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The reason to get this error is x and v have different dimensions. the dimensions of x is 2 and the dimension of v is 1

Problem 4

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [ ]:
inverse = np.linalg.inv(A)
identityMatrix = np.dot(A, inverse)
identityMatrix = np.round(identityMatrix, decimals=5)
print(identityMatrix)

[[1. 0.]
 [0. 1.]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

if np.array_equal(AB, BA):
    print("\nAB = BA")
else:
    print("\nAB != BA")


AB != BA


In [ ]:
abTranspose = np.transpose(AB)
BtAt = np.dot(np.transpose(B), np.transpose(A))

if np.array_equal(abTranspose, BtAt):
    print("\n(AB)^T = B^T * A^T")
else:
    print("\n(AB)^T != B^T * A^T")


(AB)^T = B^T * A^T


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

AinvMatrix = np.linalg.inv(A)
result = np.dot(AinvMatrix, B)
print(result)

[ 2.  1. -2.]


Experiment

In [1]:
import time
import numpy as np

In [2]:
size = 1000000
matSize = 1000

In [4]:
lst1 = [i for i in range(size)]
lst2 = [i for i in range(size)]

In [6]:
Arr1 = np.arange(size)
Arr2 = np.arange(size)

In [19]:
#Element wise Addition
strtTime = time.perf_counter()
lstAdd = [lst1[i] + lst2[i] for i in range(size)]
lstAdditionTime = time.perf_counter() - strtTime
print(f"Time taken for this operation on python lists : {lstAdditionTime:.5f} seconds")

Time taken for this operation on python lists : 0.15927 seconds


In [20]:
strtTime1 = time.perf_counter()
numpyAdd = Arr1 + Arr2
numpyAddTime = time.perf_counter() - strtTime1
print(f"Time taken for this operation on Numpy array: {numpyAddTime:.5f} seconds")

Time taken for this operation on Numpy array: 0.00289 seconds


In [17]:
#Element wise Multiplication
strtTime = time.perf_counter()
lstmul = [lst1[i] * lst2[i] for i in range(size)]
listMulTime = time.perf_counter() - strtTime
print(f"\nTime taken for this operation on Python Lists: {listMulTime:.5f} seconds")


Time taken for this operation on Python Lists: 0.09273 seconds


In [18]:
strtTime1 = time.perf_counter()
numpyMul = Arr1 * Arr2
numpyMulTime = time.perf_counter() - strtTime1
print(f"Time taken for this operation on Numpy array: {numpyMulTime:.5f} seconds")

Time taken for this operation on Numpy array: 0.00526 seconds


In [15]:
#Dot Product
strtTime = time.perf_counter()
dotProduct = sum(lst1[i] * lst2[i] for i in range(size))
lstDotTime = time.perf_counter() - strtTime
print(f"\nTime taken for this operation on Python Lists: {lstDotTime:.5f} seconds")




Time taken for this operation on Python Lists: 0.11365 seconds


In [16]:
strtTime1 = time.perf_counter()
numpyDotProd = np.dot(Arr1, Arr2)
numpyDotTime = time.perf_counter() - strtTime1
print(f"Time taken for this operation on Numpy array: {numpyDotTime:.5f} seconds")

Time taken for this operation on Numpy array: 0.00244 seconds


In [21]:
#Matrix Multiplication
lstMatrix1 = [[i for i in range(matSize)] for j in range(matSize)]
lstMatrix2 = [[i for i in range(matSize)] for j in range(matSize)]

In [22]:
numpy_matrix1 = np.arange(matSize ** 2).reshape(matSize, matSize)
numpy_matrix2 = np.arange(matSize ** 2).reshape(matSize, matSize)

In [ ]:
strtTime = time.perf_counter()
tMatrix = list(zip(*lstMatrix2))
resultMat = [[sum(a * b for a, b in zip(row, col)) for col in tMatrix] for row in lstMatrix1]
lstMatMulTime = time.perf_counter() - strtTime
print(f"\nTime taken for this operation on Python List: {lstMatMulTime:.5f} seconds")

In [ ]:
strtTime1 = time.perf_counter()
numpyMatMul = np.matmul(numpy_matrix1, numpy_matrix2)
numpyMatMulTime = time.perf_counter() - strtTime1
print(f"Time taken for this operation on Numpy array: {numpyMatMulTime:.5f} seconds")